# Site settings
title: Learning To Code
header-img: img/home-bg.png
email: derekjmaloney@gmail.com
copyright_name: derekjmaloney
description: > # this means to ignore newlines until "baseurl:"
  Learning code while dealing with heart problems
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  derekjmaloney
learn_profile: derekjmaloney
email_username: derekjmaloney@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
